# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [ ]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [ ]:
# your code here
print(np)

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [ ]:
# Method 1

a = np.random.rand(1,3,5)

In [ ]:
# Method 2

np.random.randint(2, size=10)

array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [ ]:
# Method 3

np.random.randint([1, 3, 5, 7], [[10], [20]])

array([[ 7,  9,  6,  9],
       [ 6,  8,  7, 12]])

#### 4. Print *a*.


In [ ]:
# your code here

print(a)

[[[0.72004846 0.69704831 0.4088457  0.81733594 0.65195209]
  [0.6513372  0.98453453 0.76828548 0.84314598 0.7232271 ]
  [0.33206135 0.86534755 0.11608016 0.4036475  0.77129195]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [ ]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [ ]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [ ]:
# your code here

a == b

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here

x = a + b
x

ValueError: operands could not be broadcast together with shapes (1,3,5) (5,2,3)

SyntaxError: ignored

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [ ]:
# your code here

c = b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [ ]:
# your code/answer here

d = a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
# your code/answer here

print(a)
print()
print(d)

[[[0.72004846 0.69704831 0.4088457  0.81733594 0.65195209]
  [0.6513372  0.98453453 0.76828548 0.84314598 0.7232271 ]
  [0.33206135 0.86534755 0.11608016 0.4036475  0.77129195]]]

[[[1.72004846 1.69704831 1.4088457  1.81733594 1.65195209]
  [1.6513372  1.98453453 1.76828548 1.84314598 1.7232271 ]
  [1.33206135 1.86534755 1.11608016 1.4036475  1.77129195]]

 [[1.72004846 1.69704831 1.4088457  1.81733594 1.65195209]
  [1.6513372  1.98453453 1.76828548 1.84314598 1.7232271 ]
  [1.33206135 1.86534755 1.11608016 1.4036475  1.77129195]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here

e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

e == a


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

d_min = d.min()
d_max = d.max()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

f = np.zeros(shape=(2, 3, 5))

f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here

f1 = [25 if d_min<item<d_mean else 75 if d_mean<item< d_max else 0 if item == d_min else 100 for out_list in d for in_list in out_list for item in in_list]

f2 = np.array(f1)
f2

array([ 75,  75,  25,  75,  75,  75, 100,  75,  75,  75,  25,  75,   0,
        25,  75,  75,  75,  25,  75,  75,  75, 100,  75,  75,  75,  25,
        75,   0,  25,  75])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

print(d)
print()
print(f2)

[[[1.72004846 1.69704831 1.4088457  1.81733594 1.65195209]
  [1.6513372  1.98453453 1.76828548 1.84314598 1.7232271 ]
  [1.33206135 1.86534755 1.11608016 1.4036475  1.77129195]]

 [[1.72004846 1.69704831 1.4088457  1.81733594 1.65195209]
  [1.6513372  1.98453453 1.76828548 1.84314598 1.7232271 ]
  [1.33206135 1.86534755 1.11608016 1.4036475  1.77129195]]]

[ 75  75  25  75  75  75 100  75  75  75  25  75   0  25  75  75  75  25
  75  75  75 100  75  75  75  25  75   0  25  75]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here


f3 = ["A" if d_min<item<d_mean else "B" if d_mean<item< d_max else "C" if item == d_min else "D" for out_list in d for in_list in out_list for item in in_list]

f4 = np.array(f3)
f4

array(['B', 'B', 'A', 'B', 'B', 'B', 'D', 'B', 'B', 'B', 'A', 'B', 'C',
       'A', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'D', 'B', 'B', 'B', 'A',
       'B', 'C', 'A', 'B'], dtype='<U1')